### ISSUE TITLE
Question on having home-manager in your PATH

### ISSUE THREAD

**Issue by yeoffrey** [AlexNabokikh/nix-config#5]
Maybe a dumb question, so sorry!

I'm studying your `flake.nix` file and am trying to replicate the way that you have separated your darwin configuration from your home-manager configuration.

I was wondering how you have `home-manager` in your path after installation? I can't seem to find anyone else with the problem, so I'm wondering if I've setup my flake wrong. I have a simliar `mkDarwinConfiguration` function in my flake but I'm adding my home-manager as a module in there.

Do you mind giving me some insight?

Edit: I should also note that I'm working on darwin right now.

**Comment by AlexNabokikh** [comment]
This is not a dumb question at all. Let me try to explain how my setup differs from common configurations.

There are two main approaches to using home-manager with NixOS/nix-darwin:

1. The common approach: Including home-manager as a module within your NixOS/nix-darwin configuration
2. My approach: Keeping home-manager configuration completely separate

I chose the second approach because it gives me the flexibility to rebuild home-manager and system configurations independently. In my setup:

- System configuration (NixOS/nix-darwin) manages system-level settings
- Home-manager manages user-specific configurations

To see how this works, look at my home configuration files (example: https://github.com/AlexNabokikh/nix-config/blob/master/home/nabokikh/nabokikh-mac.nix#L8) where home-manager is enabled specifically for Mac machine.

The reason you don't have home-manager in your PATH is that it needs to be bootstrapped first. Here's how to set it up on a new machine:

1. First, get the required tools:
```
nix-shell -p git home-manager
```

2. Clone the configuration:
```
git clone https://github.com/AlexNabokikh/nix-config
```

3. Apply both configurations:
```
sudo nixos-rebuild switch --flake .#<computer_name> && home-manager switch --flake .#<user_name>@<computer_name>
```

After this initial setup, you can rebuild configurations separately and home-manager will be available without additional steps:
- For system: `sudo nixos-rebuild switch --flake .`
- For home-manager: `home-manager switch --flake .`

I hope it makes more sense now, but let me know if you need any clarification on specific parts of the setup.

**Comment by yeoffrey** [comment]
Hey dude! Thanks for the great write up. I followed your instructions and it worked great! I also now understand that `home-manager` is its own thing which helps me understand how they can exist separately. I didn't realize that you can just add `home-manager` from `nix-shell`, which is pretty neat!

I hope you don't mind, but I've been using your config to learn some of the more interesting parts of the nix language, so thats been super helpful. Thanks a ton!
